### ISSUE TITLE
Apt Found No Kernel Update on 24.02 Release

### ISSUE THREAD

**Issue by alive4ever** [armbian/mirror#16] opened 2024-03-02 14:29 UTC
Dear Armbian Developers!

Usually, with every quarterly Armbian release, there is a kernel update installable via apt for users running the stable build.

As for 24.02 release, there is no kernel update. So I decided to open a web browser and viewing the contents of armbian apt repository.

Actually, there are new kernel files on the mirror directory listing (version 6.6.16) with *maybe* wrong filename (23.2 instead of 24.2).

<details>
<img src="https://github.com/armbian/mirror/assets/7654911/67e39c08-cae1-4c22-ad97-51b629ee4ce7">Screenshot of mirror files</img>
</details>

It would be better to get this fixed so users can enjoy the newer kernel included with the 24.02 release.

**Comment by igorpecovnik** [comment] 2024-03-02 14:37
working on it ...

> maybe wrong filename

Yes, that was. Now recreating ... takes time.

**Comment by Nardol** [comment] 2024-03-02 17:28
Is it the reason why Armbian mirrors have no RELEASE file for E.G. Bookworm which make not possible to run `apt update` for the moment?
I prefer asking here instead of opening a new issue if the cause is here.

**Comment by igorpecovnik** [comment] 2024-03-02 18:20
The reason is that repository management is broken to some degree and we are working on it ... and doing life in between ... It will be fixed when moon gets in the perfect position. In case you want to help debugging, most of the scripts are here
https://github.com/armbian/os/tree/main/.github/workflows
:)

**Comment by igorpecovnik** [comment] 2024-03-02 20:50
Should be fixed now.

**Closed as completed by igorpecovnik** 2024-03-02 20:50 UTC

**Comment by Nardol** [comment] 2024-03-03 11:37
Nice to see moon got in the perfect position so quickly, thanks a lot and well done :+1:

**Comment by magicianalex** [comment] 2024-03-10 20:36
Hi All.
for elegoo neptune 4pro 
had the same problem:
```
sudo apt update
Hit:1 http://deb.debian.org/debian buster InRelease
Hit:2 http://deb.debian.org/debian buster-updates InRelease              
Hit:3 http://security.debian.org buster/updates InRelease                
Hit:4 http://deb.debian.org/debian buster-backports InRelease            
Ign:5 http://fi.mirror.armbian.de/apt buster InRelease                   
Err:6 http://fi.mirror.armbian.de/apt buster Release
  404  Not Found [IP: 65.21.120.247 80]
Reading package lists... Done
E: The repository 'http://apt.armbian.com buster Release' no longer has a Release file.
N: Updating from such a repository can't be done securely, and is therefore disabled by default.
N: See apt-secure(8) manpage for repository creation and user configuration details.
```

**Comment by Nardol** [comment] 2024-03-11 08:20
Is Buster still supported by Armbian?

**Comment by allcoolusernamesaregone** [comment] 2024-04-02 15:39
Also getting this issue :( :
The repository 'http://apt.armbian.com buster Release' no longer has a Release file. 
What can I do?
